[2022-07-05 10:13:49,086] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rules.task1 manual__2022-07-05T10:13:47.766751+00:00 [queued]>
[2022-07-05 10:13:49,143] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rules.task1 manual__2022-07-05T10:13:47.766751+00:00 [queued]>
[2022-07-05 10:13:49,143] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 10:13:49,143] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-05 10:13:49,143] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 10:13:49,229] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): task1> on 2022-07-05 10:13:47.766751+00:00
[2022-07-05 10:13:49,257] {standard_task_runner.py:52} INFO - Started process 2296 to run task
[2022-07-05 10:13:49,286] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_rules', 'task1', 'manual__2022-07-05T10:13:47.766751+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/triggers_rules.py', '--cfg-path', '/tmp/tmpe3a_uyl3', '--error-file', '/tmp/tmpnwijp9nd']
[2022-07-05 10:13:49,286] {standard_task_runner.py:80} INFO - Job 149: Subtask task1
[2022-07-05 10:13:49,475] {task_command.py:370} INFO - Running <TaskInstance: trigger_rules.task1 manual__2022-07-05T10:13:47.766751+00:00 [running]> on host dfb99dfc9d64
[2022-07-05 10:13:49,892] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_rules
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-05T10:13:47.766751+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-05T10:13:47.766751+00:00
[2022-07-05 10:13:49,895] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-05 10:13:49,896] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'exit 1']
[2022-07-05 10:13:49,951] {subprocess.py:85} INFO - Output:
[2022-07-05 10:13:49,965] {subprocess.py:96} INFO - Command exited with return code 1
[2022-07-05 10:13:50,034] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-07-05 10:13:50,054] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=trigger_rules, task_id=task1, execution_date=20220705T101347, start_date=20220705T101349, end_date=20220705T101350
[2022-07-05 10:13:50,146] {standard_task_runner.py:97} ERROR - Failed to execute job 149 for task task1 (Bash command failed. The command returned a non-zero exit code 1.; 2296)
[2022-07-05 10:13:50,205] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-05 10:13:50,371] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
