[2022-07-05 10:15:19,789] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rules.task1 manual__2022-07-05T10:15:18.599943+00:00 [queued]>
[2022-07-05 10:15:19,827] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rules.task1 manual__2022-07-05T10:15:18.599943+00:00 [queued]>
[2022-07-05 10:15:19,828] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 10:15:19,830] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-05 10:15:19,830] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 10:15:19,901] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): task1> on 2022-07-05 10:15:18.599943+00:00
[2022-07-05 10:15:19,919] {standard_task_runner.py:52} INFO - Started process 2367 to run task
[2022-07-05 10:15:19,939] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_rules', 'task1', 'manual__2022-07-05T10:15:18.599943+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/triggers_rules.py', '--cfg-path', '/tmp/tmpxx6hj_48', '--error-file', '/tmp/tmpavtm74tv']
[2022-07-05 10:15:19,953] {standard_task_runner.py:80} INFO - Job 151: Subtask task1
[2022-07-05 10:15:20,076] {task_command.py:370} INFO - Running <TaskInstance: trigger_rules.task1 manual__2022-07-05T10:15:18.599943+00:00 [running]> on host dfb99dfc9d64
[2022-07-05 10:15:20,337] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_rules
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-05T10:15:18.599943+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-05T10:15:18.599943+00:00
[2022-07-05 10:15:20,352] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-05 10:15:20,356] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'exit 1']
[2022-07-05 10:15:20,392] {subprocess.py:85} INFO - Output:
[2022-07-05 10:15:20,413] {subprocess.py:96} INFO - Command exited with return code 1
[2022-07-05 10:15:20,470] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-07-05 10:15:20,482] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=trigger_rules, task_id=task1, execution_date=20220705T101518, start_date=20220705T101519, end_date=20220705T101520
[2022-07-05 10:15:20,527] {standard_task_runner.py:97} ERROR - Failed to execute job 151 for task task1 (Bash command failed. The command returned a non-zero exit code 1.; 2367)
[2022-07-05 10:15:20,573] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-05 10:15:20,718] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
