[2022-07-22 06:14:55,217] {processor.py:153} INFO - Started process (PID=87) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:14:55,247] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:14:55,257] {logging_mixin.py:115} INFO - [2022-07-22 06:14:55,257] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:14:55,498] {logging_mixin.py:115} INFO - [2022-07-22 06:14:55,497] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:14:55,499] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:14:55,919] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.745 seconds
[2022-07-22 06:15:26,840] {processor.py:153} INFO - Started process (PID=115) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:15:26,883] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:15:26,884] {logging_mixin.py:115} INFO - [2022-07-22 06:15:26,884] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:15:27,050] {logging_mixin.py:115} INFO - [2022-07-22 06:15:27,049] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:15:27,050] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:15:27,277] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.441 seconds
[2022-07-22 06:15:57,981] {processor.py:153} INFO - Started process (PID=145) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:15:57,985] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:15:57,986] {logging_mixin.py:115} INFO - [2022-07-22 06:15:57,986] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:15:58,042] {logging_mixin.py:115} INFO - [2022-07-22 06:15:58,041] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:15:58,043] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:15:58,166] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.210 seconds
[2022-07-22 06:19:27,512] {processor.py:153} INFO - Started process (PID=77) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:19:27,529] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:19:27,529] {logging_mixin.py:115} INFO - [2022-07-22 06:19:27,529] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:19:27,594] {logging_mixin.py:115} INFO - [2022-07-22 06:19:27,593] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:19:27,594] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:19:27,690] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.209 seconds
[2022-07-22 06:19:58,727] {processor.py:153} INFO - Started process (PID=100) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:19:58,733] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:19:58,753] {logging_mixin.py:115} INFO - [2022-07-22 06:19:58,752] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:19:58,809] {logging_mixin.py:115} INFO - [2022-07-22 06:19:58,808] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:19:58,809] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:19:58,946] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.246 seconds
[2022-07-22 06:25:28,328] {processor.py:153} INFO - Started process (PID=83) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:25:28,335] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:25:28,337] {logging_mixin.py:115} INFO - [2022-07-22 06:25:28,337] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:25:28,372] {logging_mixin.py:115} INFO - [2022-07-22 06:25:28,367] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:25:28,375] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:25:28,446] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.130 seconds
[2022-07-22 06:25:59,042] {processor.py:153} INFO - Started process (PID=114) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:25:59,043] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:25:59,043] {logging_mixin.py:115} INFO - [2022-07-22 06:25:59,043] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:25:59,057] {logging_mixin.py:115} INFO - [2022-07-22 06:25:59,056] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:25:59,058] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:25:59,083] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.045 seconds
[2022-07-22 06:26:31,242] {processor.py:153} INFO - Started process (PID=151) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:26:31,245] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:26:31,247] {logging_mixin.py:115} INFO - [2022-07-22 06:26:31,247] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:26:31,274] {logging_mixin.py:115} INFO - [2022-07-22 06:26:31,273] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:26:31,277] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:26:31,306] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.070 seconds
[2022-07-22 06:27:04,030] {processor.py:153} INFO - Started process (PID=188) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:27:04,040] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:27:04,041] {logging_mixin.py:115} INFO - [2022-07-22 06:27:04,041] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:27:04,099] {logging_mixin.py:115} INFO - [2022-07-22 06:27:04,098] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:27:04,112] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:27:04,163] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.153 seconds
[2022-07-22 06:27:35,222] {processor.py:153} INFO - Started process (PID=223) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:27:35,227] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:27:35,228] {logging_mixin.py:115} INFO - [2022-07-22 06:27:35,228] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:27:35,256] {logging_mixin.py:115} INFO - [2022-07-22 06:27:35,254] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:27:35,257] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:27:35,286] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.076 seconds
[2022-07-22 06:28:07,161] {processor.py:153} INFO - Started process (PID=260) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:28:07,165] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:28:07,166] {logging_mixin.py:115} INFO - [2022-07-22 06:28:07,166] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:28:07,205] {logging_mixin.py:115} INFO - [2022-07-22 06:28:07,188] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:28:07,205] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:28:07,246] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.124 seconds
[2022-07-22 06:28:39,335] {processor.py:153} INFO - Started process (PID=296) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:28:39,341] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:28:39,343] {logging_mixin.py:115} INFO - [2022-07-22 06:28:39,343] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:28:39,374] {logging_mixin.py:115} INFO - [2022-07-22 06:28:39,373] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:28:39,378] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:28:39,424] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.104 seconds
[2022-07-22 06:29:10,152] {processor.py:153} INFO - Started process (PID=326) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:29:10,161] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:29:10,162] {logging_mixin.py:115} INFO - [2022-07-22 06:29:10,162] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:29:10,190] {logging_mixin.py:115} INFO - [2022-07-22 06:29:10,189] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:29:10,192] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:29:10,242] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.107 seconds
[2022-07-22 06:29:45,189] {processor.py:153} INFO - Started process (PID=366) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:29:45,199] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:29:45,213] {logging_mixin.py:115} INFO - [2022-07-22 06:29:45,213] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:29:45,271] {logging_mixin.py:115} INFO - [2022-07-22 06:29:45,270] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:29:45,285] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:29:45,366] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.192 seconds
[2022-07-22 06:30:16,230] {processor.py:153} INFO - Started process (PID=398) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:30:16,236] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:30:16,241] {logging_mixin.py:115} INFO - [2022-07-22 06:30:16,241] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:30:16,270] {logging_mixin.py:115} INFO - [2022-07-22 06:30:16,269] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:30:16,276] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:30:16,333] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.119 seconds
[2022-07-22 06:30:47,303] {processor.py:153} INFO - Started process (PID=428) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:30:47,303] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:30:47,304] {logging_mixin.py:115} INFO - [2022-07-22 06:30:47,304] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:30:47,318] {logging_mixin.py:115} INFO - [2022-07-22 06:30:47,317] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:30:47,318] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:30:47,373] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.074 seconds
[2022-07-22 06:31:19,535] {processor.py:153} INFO - Started process (PID=461) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:31:19,539] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:31:19,543] {logging_mixin.py:115} INFO - [2022-07-22 06:31:19,543] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:31:19,560] {logging_mixin.py:115} INFO - [2022-07-22 06:31:19,559] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:31:19,562] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:31:19,592] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.060 seconds
[2022-07-22 06:31:54,723] {processor.py:153} INFO - Started process (PID=506) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:31:54,744] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:31:54,748] {logging_mixin.py:115} INFO - [2022-07-22 06:31:54,748] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:31:54,895] {logging_mixin.py:115} INFO - [2022-07-22 06:31:54,894] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:31:54,907] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:31:55,102] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.422 seconds
[2022-07-22 06:32:29,180] {processor.py:153} INFO - Started process (PID=536) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:32:29,186] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:32:29,193] {logging_mixin.py:115} INFO - [2022-07-22 06:32:29,192] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:32:29,237] {logging_mixin.py:115} INFO - [2022-07-22 06:32:29,232] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:32:29,237] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:32:29,296] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.120 seconds
[2022-07-22 06:33:00,211] {processor.py:153} INFO - Started process (PID=570) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:33:00,217] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:33:00,217] {logging_mixin.py:115} INFO - [2022-07-22 06:33:00,217] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:33:00,236] {logging_mixin.py:115} INFO - [2022-07-22 06:33:00,235] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:33:00,240] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:33:00,262] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.055 seconds
[2022-07-22 06:33:33,211] {processor.py:153} INFO - Started process (PID=599) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:33:33,231] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:33:33,241] {logging_mixin.py:115} INFO - [2022-07-22 06:33:33,241] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:33:33,314] {logging_mixin.py:115} INFO - [2022-07-22 06:33:33,313] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:33:33,342] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:33:33,463] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.286 seconds
[2022-07-22 06:34:03,682] {processor.py:153} INFO - Started process (PID=629) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:34:03,693] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:34:03,698] {logging_mixin.py:115} INFO - [2022-07-22 06:34:03,698] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:34:03,767] {logging_mixin.py:115} INFO - [2022-07-22 06:34:03,766] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:34:03,787] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:34:03,892] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.229 seconds
[2022-07-22 06:34:35,017] {processor.py:153} INFO - Started process (PID=661) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:34:35,017] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:34:35,018] {logging_mixin.py:115} INFO - [2022-07-22 06:34:35,018] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:34:35,118] {logging_mixin.py:115} INFO - [2022-07-22 06:34:35,117] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:34:35,118] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:34:35,217] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.204 seconds
[2022-07-22 06:35:06,768] {processor.py:153} INFO - Started process (PID=698) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:35:06,784] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:35:06,785] {logging_mixin.py:115} INFO - [2022-07-22 06:35:06,784] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:35:06,844] {logging_mixin.py:115} INFO - [2022-07-22 06:35:06,843] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:35:06,845] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:35:06,986] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.230 seconds
[2022-07-22 06:35:37,515] {processor.py:153} INFO - Started process (PID=732) to work on /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:35:37,516] {processor.py:641} INFO - Processing file /opt/airflow/dags/big_data_pipeline.py for tasks to queue
[2022-07-22 06:35:37,535] {logging_mixin.py:115} INFO - [2022-07-22 06:35:37,534] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:35:37,592] {logging_mixin.py:115} INFO - [2022-07-22 06:35:37,591] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/big_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/big_data_pipeline.py", line 7, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-07-22 06:35:37,604] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/big_data_pipeline.py
[2022-07-22 06:35:37,675] {processor.py:161} INFO - Processing /opt/airflow/dags/big_data_pipeline.py took 0.175 seconds
